import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Play } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Header } from "@/components/layout/Header";
import { Panel } from "@/components/ui/Panel";
import { getExercise } from "@/data/exercises";
export default function ExerciseDetailPage({ params }: { params: { id: string } }) { const exercise = getExercise(params.id); if (!exercise) return notFound(); return <AppShell><Header title={exercise.name}/><section className="relative mb-3.5 h-[260px] overflow-hidden rounded-[36px] border border-white/15 bg-[#070907] shadow-card"><Image src={exercise.heroImage} alt={exercise.name} fill className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.1),#030503_92%)]"/><div className="absolute bottom-7 left-5 right-5"><small className="font-semibold text-white/80">{exercise.part}</small><h1 className="mt-1 text-[40px] font-extrabold leading-none tracking-[-1.4px]">{exercise.name}</h1></div></section><Panel><div className="mb-3 grid grid-cols-3 rounded-full border border-white/10 bg-white/[.035] p-1"><button className="h-10 rounded-full text-iron-muted">ภาพรวม</button><button className="h-10 rounded-full text-iron-muted">กล้ามเนื้อ</button><button className="h-10 rounded-full bg-iron-accent/10 font-bold text-iron-accent shadow-[inset_0_-2px_0_#A7FF1A]">วิธีการเล่น</button></div>{exercise.steps.map((step, index) => <div key={step.title} className="mb-2.5 grid grid-cols-[112px_1fr] items-center gap-3 rounded-[22px] border border-white/[.08] bg-white/[.045] p-2.5 text-left"><Image src={step.image} alt={step.title} width={224} height={172} className="h-[86px] w-[112px] rounded-2xl object-cover"/><div><strong className="mb-1 block"><span className="mr-2 inline-grid h-6 w-6 place-items-center rounded-full bg-iron-accent text-xs text-[#071004]">{index + 1}</span>{step.title}</strong><small className="text-iron-muted">{step.description}</small></div></div>)}<Link href="/train" className="mt-4 grid h-[54px] place-items-center rounded-[19px] bg-gradient-to-br from-iron-accent to-iron-accent2 font-extrabold text-[#071004] shadow-glow"><span className="inline-flex items-center gap-2"><Play size={18}/> เริ่มท่านี้</span></Link></Panel></AppShell>; }
